### ISSUE TITLE
Trying to compile Example project - Module 'RUA' not found

### ISSUE THREAD

**Issue by chimura** [clover/remote-pay-ios-go#1]
I've downloaded this repository code, and I'm trying to execute the example project, but it throws me the following error:

/Users/chimura/me/remote-pay-ios-go-3.3.2/Example/Pods/CloverGoSDK/CloverGoReaderSDK.framework/Headers/CloverGoReaderSDK-Swift.h:167:9: Module 'RUA' not found

Steps to reproduce: download the code, pod install, open xcworkspace, build

**Comment by marcos-soares** [comment]
@madhavsahuclover, It is this mistake that is happening to me too.

**Comment by madhavsahuclover** [comment]
@chimura @marcos-soares Which Xcode version are you guys using ?

**Comment by marcos-soares** [comment]
@madhavsahuclover 10.1

**Comment by chimura** [comment]
10.1, too

**Comment by madhavsahuclover** [comment]
Thanks guys for the patience, we are looking into this issue....will fix asap and update here

**Comment by madhavsahuclover** [comment]
Can you copy paste this module.modulemap file in your pod folder /Pods and if you get any error regarding libc6++ error.....remove this library from Other linker flags in build setting from your app target..In the meanwhile we will work on fixing this in our latest pod release...Thanks and let me know if there are any questions
[module.modulemap.zip](https://github.com/clover/remote-pay-ios-go/files/3020245/module.modulemap.zip)

**Comment by madhavsahuclover** [comment]
Let me know if this worked for you guys @chimura @marcos-soares

**Comment by chimura** [comment]
Copied the file to:
/Users/chimura/me/remote-pay-ios-go-3.3.2/Example/Pods/

By dragging and dropping the file to Xcode's groups hierarchy. I had "Copy items if needed", and tried selecting "Add to Targets: GoConnector", and also not selecting anything.

Tried to compile multiple times, cleared DeliveredData, still getting the exact same error.

![Screen Shot 2019-03-30 at 11 48 55](https://user-images.githubusercontent.com/3922494/55277710-d66b8280-52e1-11e9-8468-ab2ac470a82d.png)

**Comment by marcos-soares** [comment]
Me too, same mistake

**Comment by madhavsahuclover** [comment]
In the meanwhile i will publish the new pod with this issue resolved. Thanks for the patience

**Comment by chimura** [comment]
I successfully added the module.modulemap, tried to build and now I'm getting linker error:

Tried to remove CloverGoSDK from the flags, still getting linker error.

**Comment by madhavsahuclover** [comment]
if you get any error regarding libc6++ error in linking issue.....remove this library from Other linker flags in build setting from your app target..In the meanwhile we will work on fixing this in our latest pod release...Thanks and let me know if there are any questions

And also remove the repo and again copy the repo and do pod install and copy paste module.modulemap in the destination folder

**Comment by marcos-soares** [comment]
@madhavsahuclover sorry for the inconvenience, but I've done this procedure several times and still yes the error of @chimura above. 

I needed to deploy Clover Go in my project, when is the release ready with the fix?

**Comment by madhavsahuclover** [comment]
@chimura @marcos-soares can you guys check now and again clone and install new pod and run your project. Everything should go fine now

**Comment by marcos-soares** [comment]
It worked! Thanks @madhavsahuclover.
